{
 "title": "Video Stream Analytics",
 "time": { "from": "now-5m", "to": "now-1m" },
 "refresh": "1s",
 "panels": [
  {
   "title": "camera:0",
   "type": "text",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "content": "<div style='display: flex; justify-content: center;'><img src='http://localhost:8045/video?'></div>"
  },
  {
   "title": "People count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "people{camera=\"0\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "people_avg_1m{camera=\"0\"}",
     "legendFormat": "Avg[1m]"
    },
    {
     "expr": "people_max_1m{camera=\"0\"}",
     "legendFormat": "Max[1m]"
    },
    {
     "expr": "people_min_1m{camera=\"0\"}",
     "legendFormat": "Min[1m]"
    }
   ]
  },
  {
   "title": "Total people counted (non-unique)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 9, "x": 11, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(people{camera=\"0\"}[1m])",
     "legendFormat": "Last 1m"
    },
    {
     "expr": "sum_over_time(people{camera=\"0\"}[5m])",
     "legendFormat": "Last 5m"
    },
    {
     "expr": "sum_over_time(people{camera=\"0\"}[10m])",
     "legendFormat": "Last 10m"
    }
   ]
  },
  {
   "title": "Frame latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "prf_read{camera=\"0\"}",
     "legendFormat": "read"
    },
    {
     "expr": "prf_resize{camera=\"0\"}",
     "legendFormat": "resize"
    },
    {
     "expr": "prf_model{camera=\"0\"}",
     "legendFormat": "model"
    },
    {
     "expr": "prf_script{camera=\"0\"}",
     "legendFormat": "script"
    },
    {
     "expr": "prf_boxes{camera=\"0\"}",
     "legendFormat": "boxes"
    },
    {
     "expr": "prf_store{camera=\"0\"}",
     "legendFormat": "store"
    }
   ]
  },
  {
   "title": "Frames per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "fps" }
   ],
   "targets": [
    {
     "expr": "clamp_min(1-(out_fps{camera=\"0\"}/in_fps{camera=\"0\"}),0)",
     "legendFormat": "drop"
    },
    {
     "expr": "in_fps{camera=\"0\"}",
     "legendFormat": "input"
    },
    {
     "expr": "out_fps{camera=\"0\"}",
     "legendFormat": "output"
    }
   ]
  }
 ]
}